name: video_maker
description: Example. Make video preview

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  ffmpeg_kit_flutter: ^5.1.0
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.mp4